### ISSUE TITLE
alpha value used for the setup protocol

### ISSUE THREAD

**Issue by osagga** [NTumbleBit/NTumbleBit#105]
After looking into ClassicTumblerParameter,
https://github.com/NTumbleBit/NTumbleBit/blob/a9ae7f0f1e4fca586d801de7d8ed6cf95a28efda/NTumbleBit/ClassicTumbler/ClassicTumblerParameters.cs#L407
 I've noticed that the value chosen for alpha is 41. Although 41 still works and provides the needed security, for optimality reasons (shown in the table* below), the value of alpha should change to 65537.
![image](https://user-images.githubusercontent.com/5073889/37001392-9d620568-2083-11e8-807b-eb134204ec7b.png)
*The table is from the setup paper, page 8 ([here](https://eprint.iacr.org/2018/057))

**Comment by NicolasDorier** [comment]
sure, can you do a PR? it will make the check faster?

**Comment by osagga** [comment]
Yes it'll make the check faster since we would generate a fewer signatures than we would generate with alpha=41 . Nonetheless, the security provided is still strong.

PR related to this issue is #106

**Comment by nopara73** [comment]
Merged.

**Comment by goldbe** [comment]
Great thanks all!
