### ISSUE TITLE
Failed running NTumbleBit server 

### ISSUE THREAD

**Issue by Mahla-ch** [NTumbleBit/NTumbleBit#108]
I followed the instruction for running NTumbleBit. After Configuration and running the nTumbleBit server, this error occured: 

```
Using launch settings from /home/user1/NTumbleBit/NTumbleBit.ClassicTumbler.Server.CLI/Properties/launchSettings.json...
[18-05-26 15:49:31] info: Configuration:  Using HOME environment variable for initializing application data
[18-05-26 15:49:31] info: Configuration:  Configuration file set to /home/user1/.ntumblebitserver/TestNet/server.config
[18-05-26 15:49:31] info: Configuration:  Network: TestNet
[18-05-26 15:49:31] info: Configuration:  Data directory set to /home/user1/.ntumblebitserver/TestNet
[18-05-26 15:49:31] info: Configuration:  Configuration file set to /home/user1/.ntumblebitserver/TestNet/server.config
[18-05-26 15:49:31] info: Configuration:  Using cycle shorty2x
[18-05-26 15:49:31] info: Configuration:  Testing RPC connection to http://localhost:18332/
[18-05-26 15:49:31] info: Configuration:  RPC connection successfull
[18-05-26 15:49:31] fail: Configuration:  Please, fix rpc settings in /home/user1/.ntumblebitserver/TestNet/server.config
```

testnet bitcoin core is installed locally.

my bitcoin config: 

 > testnet=1
> server=1
> rpcuser=bitcoinuser
> rpcpassword=123456
> prune=2000
> listen=1
> rpcport=18332

serve config:
>  #Common Commands
> #Connection to the input wallet. TumbleBit.CLI will try to autoconfig based on default settings of Bitcoin Core.
> rpc.url=http://localhost:18332/
> rpc.user=bitcoinuser
> rpc.password=123456
> rpc.cookiefile=~/.bitcoin/.cookie

would you please help me to solve it?

**Comment by D3m0nKingx** [comment]
Change:
>rpc.cookiefile=~/.bitcoin/.cookie

rpc.cookiefile=/home/user1/.bitcoin/.cookie

**Comment by Mahla-ch** [comment]
Thank you for your respond but It didn't resolve the problem :(

**Comment by D3m0nKingx** [comment]
@NicolasDorier I had to change NTumbleBit/global.json to reflect the current version of dotnet-sdk ( v2.1.4 ) on my local copy. Is this something we need to enforce or could accept any version 2.0+ ?

**Comment by D3m0nKingx** [comment]
@Mahla-ch I think the issue is with the cookie file, I'm testing with bitcoind right now, and I don't see any cookie file being created in the datadir ... 

I added `rpccookiefile=/home/demon/.bitcoin/cookie` to my bitcoin.conf and it seems bitcoind doesn't create this file, however in the debug.log: 

`debug.log:2018-05-27 05:28:20 Generated RPC authentication cookie /home/demon/.bitcoin/cookie`


Can you confirm ?

**Comment by nopara73** [comment]
Comment out the cookie file from the server.config. You either connect through username/password or cookie file.

**Comment by Mahla-ch** [comment]
@D3m0nKingx  according to your answer about cookiefile direction, I searched about it. I think it is generated when there is no config file. when I remove my config file and run the bitcoin core, the cookie file is generated, but when I set my config file and restart the core, there is no cookie file!!

@nopara73 the error is the same when I comment the cookie line.
`#rpc.cookiefile=/home/user1/.bitcoin/.cookie`

**Comment by D3m0nKingx** [comment]
@nopara73 I confirm the same as @Mahla-ch 

@Mahla-ch now that is odd, and shouldn't be happening that way, I recall the cookie originally being generated last time I ran bitcoin-core, even with the setting in the conf :confused:

**Comment by D3m0nKingx** [comment]
I'm running bitcoin Version: 0.16.0-xenial1 installed from the ppa, and tried what you said @Mahla-ch and It's not generating any cookie whatsoever, with or without the conf file, even if i specify `-rpccookiefile` on the commandline (with no conf file) it still doesn't create it !

**Comment by Mahla-ch** [comment]
@D3m0nKingx Do you think it is about bitcoin core? or there is something wrong with config file?
It says `RPC connection successfull` in terminal, then it shows the error!!

**Comment by D3m0nKingx** [comment]
So deleted my datadir, and started bitcoind from scratch: `bitcoind -testnet -server`, and this created the .cookie file in ~/.bitcoin/testnet3/.cookie

NTumblebit is able to authenticate with the cookie, but it still says to fix rpc settings in server.config file, even so it says the ***RPC connection successful***  ... this is just weird @nopara73 you have any idea ?

Is there anyway to get more debug info from TB as to what setting is wrong in the config ?

**Comment by D3m0nKingx** [comment]
It seems it only creates the cookie as long as no rpcuser/password is set

**Comment by D3m0nKingx** [comment]
The problem with this is, when you don't have user/password set, then you can't use bitcoin-cli to control core. So I'm trying to figure out how to make `bitcoin-cli` work, because it's saying:
```
error: Could not locate RPC credentials. No authentication cookie could be found, and RPC password is not set.  See -rpcpassword and -stdinrpcpass.  Configuration file: (/home/demon/.bitcoin/bitcoin.conf)
```
And after I make a bitcoin.conf and put in the rpccookiefile=/home/demon/.bitcoin/testnet3/.cookie`, then it spits out a new error: 
```
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
```

**Comment by D3m0nKingx** [comment]
@NicolasDorier Going back to TB, I uncommented"

```
tor.enabled=true
tor.server=http://127.0.0.1:9051
tor.cookiefile=/var/lib/tor/control_auth_cookie
```
And this resulted in:

```bash
Unhandled Exception: NTumbleBit.Configuration.ConfigException: Key tor.server should be of type IPEndPoint
   at NTumbleBit.Configuration.TextFileConfiguration.GetOrDefault[T](String key, T defaultValue) in /home/demon/coins/NTumbleBit/NTumbleBit/Configuration/TextFileConfiguration.cs:line 179
   at NTumbleBit.ClassicTumbler.Client.ConnectionSettings.TorConnectionSettings.ParseConnectionSettings(String prefix, TextFileConfiguration config) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Client/ConnectionSettings/TorConnectionSettings.cs:line 27
   at NTumbleBit.ClassicTumbler.Server.TumblerConfiguration.LoadArgs(String[] args) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Server/TumblerConfiguration.cs:line 151
   at NTumbleBit.ClassicTumbler.Server.CLI.Program.Run(String[] args) in /home/demon/coins/NTumbleBit/NTumbleBit.ClassicTumbler.Server.CLI/Program.cs:line 40
   at NTumbleBit.ClassicTumbler.Server.CLI.Program.Main(String[] args) in /home/demon/coins/NTumbleBit/NTumbleBit.ClassicTumbler.Server.CLI/Program.cs:line 27
```

**Comment by Mahla-ch** [comment]
@D3m0nKingx  thanks alot for your responses :)
now I should find a way to have both user/pass set and .cookie file ... 
I see your .cookie file location is `/home/demon/.bitcoin/testnet3/.cookie`. where should .cookie file location be? in testnet folder or .bitcoin folder?

**Comment by D3m0nKingx** [comment]
By default the cookie is in ~/.bitcoin/.cookie without defining custom location with `rpccookiefile=`

**Comment by D3m0nKingx** [comment]
>now I should find a way to have both user/pass set and .cookie file ...

This is what I was trying to do. It can't be done, by setting the rpcuser/password, it affectively disables having a cookie file. That and I have seen a message saying that rpcuser/password will be deprecated,

**Comment by Mahla-ch** [comment]
In this issue on bitcoin:
https://github.com/bitcoin/bitcoin/issues/10218
they claimed that:
If the content of .cookie file is like this:
`__cookie__:3784b8eb00726c09b275aff93882b7859cf482b8f714931343fds32431234gaa`
then the user name is:` __cookie__` and the password is: `3784b8eb00726c09b275aff93882b7859cf482b8f714931343fds32431234gaa`


Do you think it can help?! 
I can not try now! because there is no .cookie file when I run bitcoin on testnet network yet! It is ok in main bitcoin network!

**Comment by D3m0nKingx** [comment]
Right, but that's for use with the cookie authentication, not as "user/password" like the rpcuser/rpcpassword methods. It's separate all together. But heck if you find a way that works let me know :)

**Comment by D3m0nKingx** [comment]
Ok I just made it work, when you're on testnet, you have to specify the cookie file location in the conf:

rpccookiefile=~/.bitcoin/testnet3/.cookie

The reason being is because I did an strace on bitcoin-cli (on testnet) and saw this:
```
open("/home/demon/.bitcoin/testnet3/.cookie", O_RDONLY) = -1 ENOENT (No such file or directory)
```
So bitcoin-cli uses a default location, and setting a custom path for the cookie in the conf to anything other than this won't work.

**Comment by D3m0nKingx** [comment]
So at this point, Bitcoin-core is working, bitcoin-cli is working, NTB Server is connecting successfully to bitcoin's rpc port and communicating, but for some reason there's some rpc settings error in the server.config file, and it's the only thing it's not clearly informing of what it is exactly. Only the trial and error I did with uncommenting one line at a time until the stack trace appeared after uncommenting the tor settings section that something came up:
```
Unhandled Exception: NTumbleBit.Configuration.ConfigException: Key tor.server should be of type IPEndPoint
```
I tried various IP addressing schemes for `tor.server=http://localhost:9051` and nothing worked.

**Comment by Mahla-ch** [comment]
would you please explain it in details? Still it is not working...
we should define conf file and .cookie path? how do you have both of them?

**Comment by D3m0nKingx** [comment]
On mainnet the bitcoin.conf file shouldn't have any user/password set, if you want to just use a cookie file.

On Testnet you need to set a conf file and define rpccookiefile=/home/<user>/.bitcoin/testnet3/.cookie

**Comment by D3m0nKingx** [comment]
### bitcoin.conf:
```
daemon=1
testnet=1
rpccookiefile=/home/demon/.bitcoin/testnet3/.cookie
```
### server.config:
```
####Common Commands####
#Connection to the input wallet. TumbleBit.CLI will try to autoconfig based on default settings of Bitcoin Core.
rpc.url=http://localhost:18332/
#rpc.user=btcnomoreforks
#rpc.password=onemoreforkbtcdead
rpc.cookiefile=/home/demon/.bitcoin/testnet3/.cookie


####Tumbler settings####
## The fees in BTC
tumbler.fee=0.01
## The cycle used among Kotori,Shorty,Shorty2x
cycle=Shorty2x

####Server Commands####
#port=37123
#listen=0.0.0.0


####Tor configuration (default is enabled, using cookie auth or no auth on Tor control port 9051)####
tor.enabled=true
tor.server=http://localhost:9051
#tor.password=mypassword
tor.cookiefile=/var/lib/tor/control_auth_cookie
#tor.virtualport=80


####Debug Commands####
#Whether or not the tumbler deliver puzzle's solution off chain to the client (default: true)
#cooperative=false
```

**Comment by NicolasDorier** [comment]
Never copy/paste the cookie as user and password. The cookie file change everytimes the node reboot!

**Comment by NicolasDorier** [comment]
`tor.server=http://127.0.0.1:9051` might be wrong try `tor.server=127.0.0.1:9051` instead.

**Comment by D3m0nKingx** [comment]
Didn't work changing to `tor.server=127.0.0.1:9051`. 

I know the cookie changes, that's why I had told him it's completely different from rpcuser/rpcpassword method.

**Comment by Mahla-ch** [comment]
@D3m0nKingx sorry again! but I couldn't resolve the problem yet! would you please help me to find the problem? all parts are the same as your config files but the error is the same as first time!:((

**Comment by NicolasDorier** [comment]
will take a look today. Long time I did not ran the project, but last time was working! :p

**Comment by NicolasDorier** [comment]
Let's move to #109
