### ISSUE TITLE
Make good use of waxwing's review

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#32]
You can find it here: https://redd.it/5xavf7  
Maybe add a link to the wiki, if people get stuck this can help. Other ideas?

**Comment by NicolasDorier** [comment]
now checking min bitcoin core version at https://github.com/NTumbleBit/NTumbleBit/commit/b1a4eafefd0a7f223f0c55b6616b5ac7b69d1765
