### ISSUE TITLE
DBreezeException; Too many open files

### ISSUE THREAD

**Issue by NicolasDorier** [NTumbleBit/NTumbleBit#35]
Error reported
```
 DBreeze.Exceptions.DBreezeException: Creation of the database folder failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: /home/xxxx/.ntumblebit/TestNet/db/Cycle_1112038/_DBreezeSchema ---> System.IO.IOException: Too many open files
```

**Comment by nopara73** [comment]
Isn't it duplicate? https://github.com/NTumbleBit/NTumbleBit/issues/30  
  
@takaya-imai Could you confirm this is duplacate?

**Comment by NicolasDorier** [comment]
Please can you try again with my fix ? It should be ok now

**Comment by takaya-imai** [comment]
@nopara73 it might be duplicate.

If I change the max open files by editing /etc/security/limits.conf on ubuntu 16.04, the errors are disappeared temporarily
but I think Tumbler should not have so many open files at the same time.

This is my setting for Tumbler process.
```
$ cat /proc/47841/limits
Limit                     Soft Limit           Hard Limit           Units
...
Max processes             27713                27713                processes
Max open files            65536                65536                files
...
```

**Comment by takaya-imai** [comment]
@NicolasDorier Thanks a lot. I'll check.

**Comment by takaya-imai** [comment]
@NicolasDorier It seems to be solved.
