### ISSUE TITLE
In order to pass CanRSASign test

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#4]
You have a test, called `CanRSASign()` in `Class1.cs`.    
It is outcommented. I suppose, because that test doesn't pass.    
I don't see the big picture yet, I just want to note if you divide the `RsaKey.KeySize` by 8 it will pass.  
  
`RandomUtils.GetBytes(RsaKey.KeySize / 8);`  
  
**Update:**  With 88be17e9997717fb29269af308920c30cc7e405d commit the `CanRSASign()` test function has been uncommented. The test still doesn't pass without dividing the `RsaKey.KeySize` by 8.

**Comment by NicolasDorier** [comment]
fixed
