### ISSUE TITLE
HidenWallet setup instructions faulty

### ISSUE THREAD

**Issue by unsystemizer** [NTumbleBit/NTumbleBit#41]
https://github.com/NTumbleBit/NTumbleBit/wiki/How-to-Run#hiddenwallet 

I get `warn : The folder '/home/user/HiddenWallet' does not contain a project to restore.`

Probably it got messed up after the recent updates.

**Comment by nopara73** [comment]
The instructions are correct.  
```
git clone https://github.com/nopara73/HiddenWallet/
cd HiddenWallet/
git checkout NTumbleBitTest
cd src/HiddenWallet/
dotnet restore
dotnet run
```  
  
I think you missed cd into src/HiddenWallet.

**Comment by unsystemizer** [comment]
@nopara73 you're right, that warning was from my 2nd attempt (I thought to try something different). 
But I get the same error by following the Wiki. Can you check?

```
Last login: Sun Apr 30 21:09:20 2017 from 192.168.1.1
testuser@ubuntu:~$ git clone https://github.com/nopara73/HiddenWallet/
Cloning into 'HiddenWallet'...
remote: Counting objects: 1086, done.
remote: Compressing objects: 100% (320/320), done.
remote: Total 1086 (delta 190), reused 0 (delta 0), pack-reused 733
Receiving objects: 100% (1086/1086), 514.13 KiB | 93.00 KiB/s, done.
Resolving deltas: 100% (653/653), done.
Checking connectivity... done.

testuser@ubuntu:~$ cd HiddenWallet/

testuser@ubuntu:~/HiddenWallet$ git checkout NTumbleBitTest
Branch NTumbleBitTest set up to track remote branch NTumbleBitTest from origin.
Switched to a new branch 'NTumbleBitTest'

testuser@ubuntu:~/HiddenWallet$ cd src/HiddenWallet/

testuser@ubuntu:~/HiddenWallet/src/HiddenWallet$ dotnet restore
warn : The folder '/home/testuser/HiddenWallet/src/HiddenWallet' does not contain a project to restore.

```

**Comment by nopara73** [comment]
I strongly suspect it's because I upgraded HiddenWallet to the new .NET Core version and NTumbleBit needs the old one. So far I haven't figured out how to have both of the version in one computer, so I'd rather wait until NTumbleBit gets up to date and not downgrade HiddenWallet.  
  
The old .NET Core needs project.json, the new one .csproj file. So it makes sense that it doesn't find project.json, because it doesn't have, it only have .csproj file.  
Sorry for this, I don't really have half a day to figure out how to have both on the system, Microsoft is pretty aggressively removing information, because it wants everyone to use the new version.

**Comment by unsystemizer** [comment]
No problem, thanks for reopening the issue. Once it's sorted out (maybe by NTumbleBit moving to the same release) we can close it. 
Should we put a link to this issue in the Wiki or leave it as-is for time being?

**Comment by nopara73** [comment]
Yes, putting a link to this issue is a good idea. Could you do that? Practice contribution a little bit? :P

**Comment by unsystemizer** [comment]
I added a note which we can remove once this is no longer a problem.

**Comment by nopara73** [comment]
Also related: https://github.com/NTumbleBit/NTumbleBit/issues/52  
Once it's resolved I remove the NTumbleBitTest branch in HiddenWallet and add support for the new version of HiddenWallet (which has GUI) to be able to be output wallet for NTumbleBit.

**Comment by nopara73** [comment]
Resolved: https://github.com/NTumbleBit/NTumbleBit/wiki/How-to-Run
