### ISSUE TITLE
Document CLI operation

### ISSUE THREAD

**Issue by unsystemizer** [NTumbleBit/NTumbleBit#42]
Is there a place where we can see a complete flow of the CLI commands, from the beginning till the end?

**Comment by NicolasDorier** [comment]
Yes here:

https://github.com/NTumbleBit/NTumbleBit/wiki

The important thing to understand is that this is a passive process, not an active one. The client command line utility just dumbly drain all the coins from the input bitcoin core wallet to and hd pubkey.

**Comment by unsystemizer** [comment]
Yes, I read the Wiki (and made changes `How to run`) but it's still find the process a bit confusing. 
I haven't tried to use it yet, for now I just got to the point where both the server and client can start. 

The link you gave mentions "from one address to another address" and I will use another Bitcoin Core instance for my wallet, so I guess what I'm supposed to see is coins sent from addresses with UTXO's and then received at newly created addresses. Is that how it's supposed to work? 

I just noticed there's a PR (https://github.com/NTumbleBit/NTumbleBit/pull/39) which contains new CLI commands. Once it's merged I'll try it out and possibly create a Wiki page for the CLI - I just need to know what CLI commands are available.

**Comment by NicolasDorier** [comment]
There is only 2 options available `-testnet` and `-onlymonitor`.

You are using Hidden Wallet as output wallet. Why is that ?
You can use Copay, or Bitcoin Core as well. I think Copay is the easiest. (or trezor/ledger since it is also using HD)

I will add some diagram to better explain the big picture.

**Comment by NicolasDorier** [comment]
#39 by itself is not that useful for now. I want it for future features.

> The link you gave mentions "from one address to another address" and I will probably use an>other Bitcoin Core instance for my wallet, so I guess what I'm supposed to see is coins sent from addresses with UTXO's and then received at newly created addresses. Is that how it's supposed to work?

Yes. You basically create your bitcoin core wallet. Then the tumbler take coins out of it and send it to address generated by a BIP32 pubkey/path, or by another bitcoin core.

**Comment by unsystemizer** [comment]
I wanted to use Hidden Wallet because that seemed the easiest based on the Wiki.

I forgot to mention: I was also wondering about "Payment Hub Mode" which isn't explained on that Wiki page - how does that model work and can the hub take a fee like in JoinMarket?

**Comment by NicolasDorier** [comment]
Payment hub mode is not yet developped.
It is a way to use TumbleBit as a trustless, privacy friendly, second layer payment system.

The Tumbler Mode is only about making sure two addresses are not linked, that the server can't link either.

**Comment by nopara73** [comment]
Until NTumbleBit upgrades to the new .NET Core version HiddenWallet is unusable if one doesn't have both .NET Core version on their system.

**Comment by nopara73** [comment]
Closing, continue here: https://github.com/NTumbleBit/NTumbleBit/issues/41
