### ISSUE TITLE
Trivial: server should wait if port open or message could be made friendlier

### ISSUE THREAD

**Issue by unsystemizer** [NTumbleBit/NTumbleBit#43]
A minor thing I noticed today: if bitcoind has been started but RPC server is still not up, TumbleServer suggests that server.config be changed:

```
info: Configuration[0]
      Testing RPC connection to http://localhost:18332/
fail: Configuration[0]
      Error connecting to RPC Rescanning...
fail: Main[0]
      Please, fix rpc settings in /home/testuser/.ntumblebitserver/TestNet/server.config

testuser@ubuntu:~/NTumbleBit/NTumbleBit.TumblerServer$ telnet localhost 18332
Trying ::1...
Connected to localhost.
Escape character is '^]'.
^C^C^CConnection closed by foreign host.

```

While not many users would start TumbleServer right away, some perhaps will and may wonder what's wrong with their configuration file. 

Suggestion: `Please, fix rpc settings ` to `Please ensure RPC server is running and accessible or fix RPC settings in` may be better and cover both this and potential firewall issues as well.

**Comment by NicolasDorier** [comment]
fixed in https://github.com/NTumbleBit/NTumbleBit/commit/e63132175cf5d84a279026bb0b3e7e46d135a5e5
