### ISSUE TITLE
Small fee for Tumbler Cashout tx and Client Cashout tx

### ISSUE THREAD

**Issue by takaya-imai** [NTumbleBit/NTumbleBit#49]
Cashout tx always has small fee in mainnet and it takes long time to confirm.
Tx in testnet seems to have the same problem but I have no detail data for the problem in testnet.

Investigating tx, I got a problem point for the small fee.
Problem is tx size estimation for both cashout txes.

I explain the problem point as below.

-----

I investigated Tumbler Cashout tx and Client Cashout tx by inserting debug codes in followings.

* NTumbleBit/NTumbleBit/PuzzlePromise/PromiseClientSession.cs
* NTumbleBit/NTumbleBit/PuzzleSolver/SolverServerSession.cs
* NTumbleBit/NTumbleBit/PuzzleSolver/SolverClientSession.cs

**Tumbler Cashout tx**

This is the Tumbler Cashout tx.
https://blockchain.info/tx/ff7d7c2cda3e02dd6d6984bd7019ecbaba26a4c1212ef6a8bcaa15b4c99a0c78
<img width="1227" alt="2017-05-23 17 48 39" src="https://cloud.githubusercontent.com/assets/2457450/26350270/93035e40-3fed-11e7-8e14-ef00316b42ca.png">

As see its tx, tx size is 843 bytes and fee per byte is 107.387 sat/Byte.

However, debug code derives the following data.

```
info: Server[0]
      CheckBlindFactors
info: Server[0]
      0.00290217 BTC/kB
CheckBlindedFactors: tx.GetVirtualSize()
83
CheckBlindedFactors: InternalState.EscrowedCoin.Redeem.Length
118
CheckBlindedFactors: InternalState.OfferTransactionFee
100124
info: Server[0]
      FulfillOffer
info: Server[0]
      0.00290217 BTC/kB
FulfillOffer: size
312
FulfillOffer: feeRate.ToString()
0.00290217 BTC/kB
FulfillOffer: feeRate.GetFee(size)
90547
FulfillOffer: fulfill.Outputs[0].Value
6809329
info: Main[0]
      Broadcaster broadcasted  b23d30f585867aa372cf16d690c2bc5bbc54fe8c98bffb5cb5c18da3a60dc7ed
```
debug codes: https://github.com/takaya-imai/NTumbleBit/blob/debug_code/NTumbleBit/PuzzleSolver/SolverServerSession.cs#L356

It implies that command estimatefee of bitcoind has proper value but size is very smaller than actual size.
Therefore actual fee becomes very small as following calculation.

```
107.387 sat/Byte = 0.00290152 BTC/kB * 100,000,000 sat / 1,000 bytes * 312 bytes / 843 bytes
```

This size is derived from EstimateScriptSigSize() so this might have something bug to estimate scriptsig size.

**Client Cashout tx**

This is the Client Cashout tx.
https://blockchain.info/tx/9db475abdc00e0b65d53fea937aa3bbb97cc0f0db403ac494287dd47b721f231
<img width="1199" alt="2017-05-23 17 48 31" src="https://cloud.githubusercontent.com/assets/2457450/26350301/a6150ace-3fed-11e7-9aa5-86ff14d107db.png">

As see its tx, tx size is 354 bytes and fee per byte is 69.661 sat/Byte.

However, debug code derives the following data.

```
info: Main[0]
      CyclePhase.TumblerChannelEstablishment
info: Main[0]
      0.00290187 BTC/kB
CreateSignatureRequest: feeRate.ToString()
0.00290187 BTC/kB
CreateSignatureRequest: cashout.GetVirtualSize()
85
CreateSignatureRequest: fee
24665
CreateSignatureRequest: cashout.Outputs[0].Value
6765335
info: Main[0]
      Tumbler escrow broadcasted b1b96247c83de6c62b07fd8040e07b3cc849860e643d944143be67a83503f991
```
debug codes: https://github.com/takaya-imai/NTumbleBit/blob/debug_code/NTumbleBit/PuzzlePromise/PromiseClientSession.cs#L252

It implies that command estimatefee of bitcoind has proper value but size is very smaller than actual size.
Therefore, actual fee becomes very small as following calculation.

```
69.661 sat/Byte = 0.00290187 BTC/kB * 100,000,000 sat / 1,000 bytes * 85 bytes / 354 bytes
```

This size is derived from GetVirtualSize() in NBitcoin so this might have something bug to estimate size.

**Comment by takaya-imai** [comment]
GetVirtualSize() in NBitcoin always returns 85 bytes in my NTumbleBit debug code for small fee.

```
$ grep GetVirtualSize -A 1 client.log
CreateSignatureRequest: cashout.GetVirtualSize()
85
--
CreateOfferRedeemTransaction: tx.GetVirtualSize()
85
--
CreateSignatureRequest: cashout.GetVirtualSize()
85
--
CreateOfferRedeemTransaction: tx.GetVirtualSize()
85
--
CreateSignatureRequest: cashout.GetVirtualSize()
85
--
CreateOfferRedeemTransaction: tx.GetVirtualSize()
85
--
CreateSignatureRequest: cashout.GetVirtualSize()
85
--
CreateOfferRedeemTransaction: tx.GetVirtualSize()
85
--
CreateSignatureRequest: cashout.GetVirtualSize()
85
--
CreateOfferRedeemTransaction: tx.GetVirtualSize()
85
```

**Comment by NicolasDorier** [comment]
have you tried since my fix on https://github.com/NTumbleBit/NTumbleBit/commit/036c2b6bb7e4805bfe236daff97b58849020fcf0 ?

**Comment by NicolasDorier** [comment]
mmhh wait a second, it seems to be something else, thanks for tracking it down will review carefully.

**Comment by NicolasDorier** [comment]
I think I fixed it can you try https://github.com/NTumbleBit/NTumbleBit/commit/f88bda2ce60eda7fdc65bcc0b9d496710ef4ee12

**Comment by takaya-imai** [comment]
@NicolasDorier thanks for review! I try https://github.com/NTumbleBit/NTumbleBit/commit/f88bda2ce60eda7fdc65bcc0b9d496710ef4ee12 .

**Comment by takaya-imai** [comment]
@NicolasDorier 
I am testing https://github.com/NTumbleBit/NTumbleBit/commit/f88bda2ce60eda7fdc65bcc0b9d496710ef4ee12
but it looks like fixing only PuzzlePromise Part(Client Cashout) but not fixing PuzzleSolver Part(Tumbler Cashout).

Do you think that below is not needed to fix to include `fulfillScript + Op.GetPushOp(offerCoin.Redeem.ToBytes())` size?
https://github.com/NTumbleBit/NTumbleBit/blob/e8b702b1d5b18a6cbf67dc9b4c81a8cc3a6c742f/NTumbleBit/PuzzleSolver/SolverServerSession.cs#L348

Similar to https://github.com/NTumbleBit/NTumbleBit/commit/f88bda2ce60eda7fdc65bcc0b9d496710ef4ee12 , I think it needs to fix as follows.
Below might have mistakes because I do not know NBitcoin grammar though.

```
                        Transaction fulfill = new Transaction();
                        fulfill.Inputs.Add(new TxIn(offerCoin.Outpoint));
                        fulfill.Outputs.Add(new TxOut(offerCoin.Amount, cashout));

                        var signature = fulfill.Inputs.AsIndexedInputs().First().Sign(InternalState.FulfillKey, offerCoin, SigHash.All);
                        var fulfillScript = SolverScriptBuilder.CreateFulfillScript(signature, solutions);
                        fulfill.Inputs[0].ScriptSig = fulfillScript + Op.GetPushOp(offerCoin.Redeem.ToBytes());

                        var tb = new TransactionBuilder();
                        tb.Extensions.Add(new EscrowBuilderExtension());
                        tb.AddCoins(InternalState.EscrowedCoin);
                        var size = tb.EstimateSize(fulfill, true);
                        var fee = feeRate.GetFee(size);

                        fulfill.Outputs[0].Value -= fee;
```

**Comment by NicolasDorier** [comment]
wow very nice. I can't believe I made same mistake three time in the code I just pushed a fix, can you try ?

**Comment by NicolasDorier** [comment]
oops, still mistake, real fix on b0f838caf89f5ce3c29f5d9ca63d31bd997ead65

**Comment by takaya-imai** [comment]
thanks, I am testing https://github.com/NTumbleBit/NTumbleBit/commit/b0f838caf89f5ce3c29f5d9ca63d31bd997ead65 now.

**Comment by takaya-imai** [comment]
this issue is solved.
