### ISSUE TITLE
Drop the forceful support of BIP44 and make it optional

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#52]
The wiki says you need to give these information to the client.config file on Copay:  
```
outputwallet.extpubkey=tpubDCv6h3AqFXzjQpLnubExzkdyHsngEicFHDsHaGgTMtiSbBXcqN3XuzGPW6hv85R7F8DuQcnJGSXV9knSoG54auiDfzSRsVFvb9QtDBwnukp
outputwallet.keypath=0
```
  
However the Copay keypath is `44'/1'/0'` or `m/44'/1'/0'` if you wish.  
  
BIP44 is not universally used. In fact [not even Bitcoin Core uses is (and won't use it in the future)](https://bitcoin.stackexchange.com/a/50079/26859).  
  
It also makes it impossible to use HiddenWallet as an output wallet. I propose to drop the forceful support of BIP44 and make it optional.

**Comment by nopara73** [comment]
Also I think we should consider using the `k` notation @jonasschnelli is using in his stackexchange answer: `m/0'/0'/k'`.  
Right now NTumbleBit only does nonhardened last key derivation, eg: `m/44'/1'/0'/k` in case of Copay. There'll be wallets those are not like this (like Bitcoin Core).

**Comment by NicolasDorier** [comment]
the extpubkey shared by copay is already 44'/1'/0' it means that the documented path create the first address at 44'/1'/0'/0/0 which is the correct first public addresss of Copay.

TB is agnostic to BIP44 and do not force anything about it.

For Bitcoin Core, I have a PR which allow HD watch only wallet which use BIP44 like trezor. https://github.com/bitcoin/bitcoin/pull/9728

Ledger also use BIP44

**Comment by nopara73** [comment]
> TB is agnostic to BIP44 and do not force anything about it.  
  
That's not true. How would you go about defining this keypath in NTumbleBit config?: `m/0'/0'/k'`   
  
> the extpubkey shared by copay is already `44'/1'/0'` it means that the documented path create the first address at `44'/1'/0'/0/0` which is the correct first public addresss of Copay.  
  
I see that clears up some confusion. In this case the `keypath` should be defined in the config file like this: `44'/1'/0'/0/k`.

**Comment by NicolasDorier** [comment]
```
I see that clears up some confusion. In this case the keypath should be defined in the config file like this: 44'/1'/0'/0/k
```
No, as TB never have the private key it can t derive on hardened path.

TB currently make no assumption about BIP44

**Comment by NicolasDorier** [comment]
have you tried since my fix on https://github.com/NTumbleBit/NTumbleBit/commit/036c2b6bb7e4805bfe236daff97b58849020fcf0 ?

**Comment by nopara73** [comment]
I see. It turnes out I had an incorrect understanding on what hardened means.  
I didn't know this code throws an exception.  
  
```
ExtKey ek = new ExtKey();
KeyPath kp = new KeyPath("0");
KeyPath hkp = new KeyPath("0'");
Console.WriteLine(ek.Derive(kp).ScriptPubKey);
Console.WriteLine(ek.Derive(hkp).ScriptPubKey);

ExtPubKey epk = ek.Neuter();
Console.WriteLine(epk.Derive(kp).ScriptPubKey);
Console.WriteLine(epk.Derive(hkp).ScriptPubKey); // System.InvalidOperationException
```
  
In this case everything is fine. I have an unused backup, nonhardened keypath in HiddenWallet, that will be perfect for NTumbleBit output wallet.
