### ISSUE TITLE
Resolve VS2017 warnings

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#55]
`MSB3026	Could not copy "C:\xxx\Microsoft.TestPlatform.CoreUtilities.resources.dll" to "bin\Debug\netcoreapp1.1\Microsoft.TestPlatform.CoreUtilities.resources.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open.`  
I have like 3-10 warning like this, these warnings were present before the updates, too.   
  
I use Windows 7.

**Comment by NicolasDorier** [comment]
This happen if a process that use those assembly is still open. I never got it.

**Comment by nopara73** [comment]
I don't think that's the case. I just fired up VS after restarting the Windows. Rebuilt the solution and got 4 warnings. I keep it open until we fix it "or magically goes away".

**Comment by NicolasDorier** [comment]
do you still have it ?

**Comment by nopara73** [comment]
No.
