### ISSUE TITLE
Add some server configuration options

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#59]
Maybe in the config file we could add some server configuration options, like denomination and what else.

**Comment by zeptin** [comment]
+1 for the denomination

**Comment by NicolasDorier** [comment]
should be just a json file dropped somewhere with all tumbler parameters as returned by GetParameters.

**Comment by NicolasDorier** [comment]
I think allowing multi runtime (several tumbler) on one server. This should be configured by command line.

**Comment by NicolasDorier** [comment]
You can now configure the fee as long as the cycle. (documented in the default config file)
