### ISSUE TITLE
Benevolent tumbler idea

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#61]
It was a todo comment in the wiki, which I deleted and moved it here, as in issue instead:  
> TODO: Maybe in the future having a benevolent tumbler who gives out money in exchange of old solved puzzle ?

**Comment by NicolasDorier** [comment]
Closing this one in favor or https://github.com/NTumbleBit/NTumbleBit/issues/76 which achieve the same thing in a simpler way.
