### ISSUE TITLE
FeeRateUnavailableException thrown when estimatefee returns bad information

### ISSUE THREAD

**Issue by zeptin** [NTumbleBit/NTumbleBit#62]
Stack trace showing exception:

```
fail: Main[0]
      Error while executing state machine 1125798: NTumbleBit.Client.Tumbler.Services.FeeRateUnavailableException: The fee rate is unavailable
         at NTumbleBit.Client.Tumbler.Services.RPCServices.RPCFeeService.GetFeeRate() in /home/x/NTumbleBit/NTumbleBit.TumblerServer/Services/RPCServices/RPCFeeService.cs:line 47
         at NTumbleBit.Client.Tumbler.PaymentStateMachine.GetFeeRate() in /home/x/NTumbleBit/NTumbleBit.Client/Tumbler/PaymentStateMachine.cs:line 324
         at NTumbleBit.Client.Tumbler.PaymentStateMachine.Update(ILogger logger) in /home/x/NTumbleBit/NTumbleBit.Client/Tumbler/PaymentStateMachine.cs:line 182
         at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0() in /home/x/NTumbleBit/NTumbleBit.Client/Tumbler/StateMachinesExecutor.cs:line 106
```

In RPCFeeService.GetFeeRate the following code is called:

```
		public FeeRate GetFeeRate()
		{
			var rate = _RPCClient.TryEstimateFeeRate(1) ??
				   _RPCClient.TryEstimateFeeRate(2) ??
				   _RPCClient.TryEstimateFeeRate(3) ??
				   FallBackFeeRate;
			if(rate == null)
				throw new FeeRateUnavailableException("The fee rate is unavailable");
			if(rate < MinimumFeeRate)
				rate = MinimumFeeRate;
			return rate;
		}
```

Note that only the last 3 blocks are considered for fee estimation.

Checking the output of the 'estimatefee' RPC call on a testnet node:

```
bitcointestnet3:~$ bitcoin-cli estimatefee 1
-1
bitcointestnet3:~$ bitcoin-cli estimatefee 2
-1
bitcointestnet3:~$ bitcoin-cli estimatefee 3
-1
bitcointestnet3:~$ bitcoin-cli estimatefee 4
0.00000987
bitcointestnet3:~$ bitcoin-cli estimatefee 5
0.00000987
bitcointestnet3:~$ bitcoin-cli estimatefee 6
0.00000987
```

It seems that the actual problem is that the fallback fee rate is not being set in the FeeService when it is initialised in ExternalServices.cs. It is therefore null when the fee estimation is attempted. This is probably more of an issue on testnet than mainnet, but the code should be made robust either way.

**Comment by nopara73** [comment]
The `FallBackFeeRate` is not set, it also breaks regtest.  
There are a number of ways to resolve it. I will implement it as soon as we come to an agreement. @NicolasDorier, @zeptin which do you think should I implement, or do you have a better idea?  
  
1. We could set the default `FallBackFeeRate` to be the `MinimumFeeRate`.  
IMO this is a bad idea, it would solve only the regtest and testnet testing.  
2. We could set the default `FallBackFeeRate` to a constant number, which "feels right".  
I feel like this is what Nicolas would do.  
3. My preferred solution: we query [BlockCypher](https://www.blockcypher.com) for `low_fee_per_kb` every hour and that will always be the actual `FallBackFeeRate`.  
And if the query fails we fall back to the 2. approach.  
Why BlockCypher? This is the only online fee estimation api that I found that doesn't outright blocks Tor IP addresses, there might be more, though.  
Alternatively we could add `estimatefee` to QBitNinja, but as we discussed before there were something wrong with that, I don't remember what. I guess that QBit doesn't use Core's RPC?

**Comment by nopara73** [comment]
At https://github.com/NTumbleBit/NTumbleBit/pull/63 I temporarily set the `FallBackFeeRate` to `MinimumFeeRate` until we figure out what the proper `FallBackFeeRate` should be. So now the testnet and regtest works properly.

**Comment by NicolasDorier** [comment]
there should have no FallBackFeeRate. If you do not have estimation, it means your bitcoin node did not run long enough time.

**Comment by NicolasDorier** [comment]
I am against adding dependency on any other service. If the fee estimation is unavailable, it should crash until the node ran long enough.

**Comment by nopara73** [comment]
Neverthless you mast have it on RegTest, because estimatefee always fails there. https://github.com/NTumbleBit/NTumbleBit/pull/64
