### ISSUE TITLE
Add version tag

### ISSUE THREAD

**Issue by takaya-imai** [NTumbleBit/NTumbleBit#69]
It is better to add version tag for development, bug fix and consensus between server and client.

**Comment by nopara73** [comment]
Fine by me. Altough it seems procrastination until a server is not run, so I won't figure out this change it.

**Comment by NicolasDorier** [comment]
Yes, but there is still no version alpha though. IMO the TOR patch is needed before making any release.

**Comment by NicolasDorier** [comment]
will do, soon v1. I am trying to tumble 100 testnet client simultaneously, then will release v1
