### ISSUE TITLE
Tor integration barrier (bug)

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#71]
There's a tricky bug when transfering chunked data in DotNetTor. Eg, this get request doesn't execute properly: http://testnet.ntumblebit.metaco.com/api/v1/tumblers/0/parameters  
  
Until it's fixed Tor cannot be integrated.  
The issue: https://github.com/nopara73/DotNetTor/issues/5

**Comment by NicolasDorier** [comment]
will you be able to fix it soon ? this is really the last piece of the puzzle. With https://github.com/NTumbleBit/NTumbleBit/issues/72

**Comment by nopara73** [comment]
Yes, but I don't know how long it will take. I am working on it full time.  
I had to go so deep that two days ago I started implementing the whole HTTP/1.1 protocol (https://tools.ietf.org/html/rfc7230 ) from scratch and hoping when I get to the chunked transfer encoding part I'll have all the knowledge I need to tackle that issue.

**Comment by NicolasDorier** [comment]
I guess we can close that now
