### ISSUE TITLE
Things to do before Release V1

### ISSUE THREAD

**Issue by NicolasDorier** [NTumbleBit/NTumbleBit#73]
~[ ] Create hidden service automatically if TOR is detected~ 
- [x] Connect Alice side through TOR or HTTP Proxy (Privoxy)
- [ ] RSA Proof for Blinding
- [x] Providing Standard Cycle defintions
- [ ] Tumbled Champagne

**Comment by NicolasDorier** [comment]
@nopara73 in v1, I think that I will just use the `TorControlClient` for configuring automatically the hidden service. Then allow a HTTP proxy to be configured for Alice. (can be directled to privoxy)

**Comment by nopara73** [comment]
> Connect Alice side through TOR or HTTP Proxy (Privoxy)  
  
Bot Bob and Alice side must be connected. A client has many Bob identities, not only one.  
Tor or Privoxy? Do you mean Tor with own HTTP proxy OR Tor with Privoxy?  
  
> Tumbled Champagne  
  
What is this?  
  
> @nopara73 in v1, I think that I will just use the TorControlClient for configuring automatically the hidden service. Then allow a HTTP proxy to be configured for Alice. (can be directled to privoxy)  
  
So you couldn't fix the bug or didn't even look at it?  
Privoxy was an option we decided against in the beginning, because "we don't want another dependency". Neverthless I continue writing my [http protocol implementation](https://github.com/nopara73/HttpProtocolTinkering/) and when it's ready, I'll easily be able to fix the chunked encoding bug in DotNetTor.

**Comment by NicolasDorier** [comment]
Tumbled champagne is the champagne of the release.

Allowing Alice side to configure a HTTP proxy is very easy to do and is not coupled with privoxy.

**Comment by NicolasDorier** [comment]
It is not possible to configure proxy for bob and alice.

**Comment by NicolasDorier** [comment]
I am removing any TOR integration for first release. With Privoxy, the user can hide Alice.

Will add TOR + Dang's UI in second version shortly after.

**Comment by NicolasDorier** [comment]
Proposal of the "Kotori" standard cycle generator.
It mix 1 BTC per day at its peak, phases of overlapping cycles are separated by at least 2 blocks, making sure same circuit is not reused, even in absense of Tor control.

```
_Kotori = new StandardCycle()
{
	FriendlyName = "Kotori",
	Consensus = consensus,
	Denomination = Money.Coins(1.0m),
	Generator = new OverlappedCycleGenerator()
	{
		RegistrationOverlap = 1,
		FirstCycle = new CycleParameters()
		{
			Start = 0,
			//one cycle per day
			RegistrationDuration = GetBlocksCount(consensus, 24 * 60) + 1,
			//make sure tor circuit get renewed
			SafetyPeriodDuration = GetBlocksCount(consensus, 20),
			ClientChannelEstablishmentDuration = GetBlocksCount(consensus, 4 * 60),
			TumblerChannelEstablishmentDuration = GetBlocksCount(consensus, 4 * 60),
			PaymentPhaseDuration = GetBlocksCount(consensus, 4 * 60 + 30),
			TumblerCashoutDuration = GetBlocksCount(consensus, 9 * 60 + 30),
			ClientCashoutDuration = GetBlocksCount(consensus, 5 * 60)
		}
	}
};
```

**Comment by NicolasDorier** [comment]
Done
