### ISSUE TITLE
Incorrect phase exception

### ISSUE THREAD

**Issue by bokobza** [NTumbleBit/NTumbleBit#74]
Hi guys,
I'm receiving an "incorrect-phase" exception. It seems the cycle for registration ends up being behind the first block received so the registration cycle is only 2 phases long instead of 3. But things seem to continue as normal to I'm not sure it it should be an exception or just an error.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/1867877/27188494-3b6cb20c-51e6-11e7-8f5d-e351fd02afa3.png)

**Comment by NicolasDorier** [comment]
This is "normal" exception

**Comment by NicolasDorier** [comment]
I should probably hide it, this happen if the client and server are slightly desynchronised.

**Comment by NicolasDorier** [comment]
it should not happen anymore. I hide this exception, except if it happened 3 times in a row. Please resubmit if you see it again.
