### ISSUE TITLE
Coin is paid in a seemingly random destination address

### ISSUE THREAD

**Issue by bokobza** [NTumbleBit/NTumbleBit#75]
Coins being paid to the destination wallet appear to be sent to a random address within it.
All the addresses with a lower index are empty.

Expected results: the coins are being paid starting at address with index 0.
Actual results: the coins are being paid at random addresses within the wallet.

**Comment by zeptin** [comment]
I can confirm this is happening. I received funds in 0/293 in my destination wallet.

Extpubkey:
tpubDDSmzg7e8fdAS1wH8ChWzZ8TkUd1FNepXHJoyGn8g653V3jSpVv48QE7dj1Va6pbmjCPL7BENiZLRUoxsL3xZmDhXTd5T7LeD2PuEeuctKm

Cashout transaction:
4d59acd36d9f81a94950cccf3be816e3dc2c92e698ff11a9e9355b3278f61241

Output wallet address:
mk24e36KKm3FTpWXp9bjpS33yvhDKJWNoD

Searching programmatically through the keys under the extpubkey, the address above is the 293rd one. This is too big a gap for Copay to detect by default (my test wallet currently has unused addresses 43-47).

**Comment by NicolasDorier** [comment]
I will add a command so you can query where are used the other keys.

**Comment by NicolasDorier** [comment]
ok now `status <address>` will show you the HD Path of the key if it belongs to the output wallet.

**Comment by NicolasDorier** [comment]
I close it for now. Reopen if you still have issues.
