### ISSUE TITLE
Feature for V2: Dropping HTTP, using plain TCP.

### ISSUE THREAD

**Issue by NicolasDorier** [NTumbleBit/NTumbleBit#80]
For now interaction between tumbler and client are using HTTP and JSON.
This has several issue: 

* Fingerprinting at HTTP Level (if multiple implementation)
* Fingerprinting at JSON level (if multiple implementation)
* Inefficient use of bandwidth

This is not a big deal for now as tumblebit has only one implementation, but this is something that should be done in V2 once it get stable and used.

**Comment by nopara73** [comment]
Concept ack.  
Notes:  
- while inefficient bandwidth use is not a problem at tumblebit, http/1.1 also not inefficient, only when there are many many rounds of requests in row. But http/2.0 fixes that.  
- We could explore I2P or Tor hidden services.  
  
However it also obsolates all 3 proxy types. Therefore if we can all agree on this goes into v2 I am not interested pushing the PR https://github.com/NTumbleBit/NTumbleBit/pull/79 anymore.

**Comment by NicolasDorier** [comment]
it does not obsolete Socks proxy.

**Comment by nopara73** [comment]
Indeed, not necessarily. My PR is still relevant then.

**Comment by NicolasDorier** [comment]
Done, now TumbleBit does not use HTTP, nor JSON for server transfer.
