### ISSUE TITLE
Certainty parameter for RSA public key

### ISSUE THREAD

**Issue by goldbe** [NTumbleBit/NTumbleBit#86]
Pointing out a small issue found by @osagga.

In NTumbleBit/RsaKey.cs (https://github.com/NTumbleBit/NTumbleBit/blob/master/NTumbleBit/RsaKey.cs#L30) you can see that the certainty parameter to generate prime numbers is hardcoded as 2.  Certainty parameter k gives  probability 1-2^{-k} that the prime p or q used to generate the RSA public key is actually prime.

The NTumbleBit code references (http://www.just.edu.jo/~tawalbeh/cpe776/notes/IEEE_DRAFT.pdf), and old IEEE Draft from 1999 (at the end of page 87 (PDF numbering).  The IEEE draft states for k (bitSize of a number) “1854-up” you would need t=2 (t is the number of tests)).

This IEEE draft is outdated by now. 

In the older version of BouncyCastle/RsaKeyPairGenerator.cs *the one that TumbleBit uses now* (https://github.com/NTumbleBit/NTumbleBit/blob/master/NTumbleBit/BouncyCastle/crypto/generators/RsaKeyPairGenerator.cs#L16) you can see that the default certainty parameter is 12 (which is higher than 2).   In the new updated version of this same bouncyCastle file (https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/generators/RsaKeyPairGenerator.cs#L23), they raised the default value of primality tests to 100.
 
I think raising certainty parameter would be a good idea. I suggest a value of 80 (since this is the security parameter for TumbleBit) or 100.

Does doing this break anything? (I doubt it would.)

**Comment by NicolasDorier** [comment]
It would only impact the duration of key creation I think. I raised to 100 c95c2c49e1e7b6f5baab5789175a239fe562824c

**Comment by goldbe** [comment]
Great, thank you.
