### ISSUE TITLE
Crypto bug in the puzzle promise protocol: signatures are not securely encrypted.

### ISSUE THREAD

**Issue by goldbe** [NTumbleBit/NTumbleBit#93]
Crypto bug found by @osagga and me:

In NTumbleBit, the ASN.1 DER encoding of the ECDSA signature produces an octet string of length 70-72 bytes [1]. However, the TumbleBit whitepaper expects the octet string of the signature to be exactly 64 bytes.  This is why the 64-byte output of SHA512 is used as a “One Time Pad” (OTP) to produce the encrypted the signature in the promise protocol.

However, in NTumbleBit the signature length is about 70 bytes but the "One Time Pad" (OTP) is 64 bytes.  To deal with this the XOR function [2] uses the OTP *twice* to XOR the excess bytes from the signature. (That is, the last 70-64=6 bytes of the signatures a XOR'd with the same 6 bytes that are XOR'd the first 6 bytes of the signature.)

This is bad. A OTP should only be used once. (Hence the name.)  See for instance https://crypto.stackexchange.com/questions/59/taking-advantage-of-one-time-pad-key-reuse.

One possible solution is the use of a “MGF1” that uses SHA512 (or SHA256) and seeded by the epsilon value to produce the pad with the specified length (in this case it would be the length of the DER signature).  Note that TumbleBit setup uses MGF1 extensively.

Another solution would be to use or introduce a different way of encoding the signature such that it’s encoded in exactly 64 bytes, that way we could still use SHA512 to produce the OTP.

[1] (from NBitcoin/NBitcoin/Crypto/ECDSASignature.cs, 
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/Crypto/ECDSASignature.cs#L81 )

This function is being called
https://github.com/NTumbleBit/NTumbleBit/blob/master/NTumbleBit/PuzzlePromise/PromiseServerSession.cs#L138
 to convert the signature to an array of bytes so that it can be passed to the XOR function here
https://github.com/NTumbleBit/NTumbleBit/blob/master/NTumbleBit/PuzzlePromise/PromiseServerSession.cs#L140

[2] from NTumbleBit/NTumbleBit/PuzzlePromise/XORKey.cs, 
https://github.com/NTumbleBit/NTumbleBit/blob/master/NTumbleBit/PuzzlePromise/XORKey.cs#L46

(You can see that the use of “i % keyHash.Length” ,given that “encrypted.Length” is larger than “KeyHash.Length”, will cause ‘i’ to wrap around and use the same bytes at the start of the hash)

**Comment by Mattyresch** [comment]
Doesn't seem like this bug would require too much additional coding, from a quick glance.

Simple fix seems like just checking the lengths prior to the loop, and extending the Length of keyHash using a padding scheme (maybe 10*1 like SHA-3), although if you want to avoid any sort of length-extension attacks a full switch to SHA-3 instead of SHA512 could probably work.

**Comment by NicolasDorier** [comment]
Thanks a lot. The best way is indeed to make the signature 64 bytes, which should not be very complicated. I am on it.

**Comment by NicolasDorier** [comment]
MMh actually I am using XOR key for something else, so I will go the MGF1 way.

**Comment by NicolasDorier** [comment]
@goldbe @osagga  Can you review https://github.com/NTumbleBit/NTumbleBit/commit/44d8f5a19fc7eeb3cd8e185eb06967491a7a2eb3 and close the issue if this is good? The tests are still passing.

**Comment by goldbe** [comment]
@NicolasDorier thanks for the fast turnaround.  It looks correct to me. 

@osagga, what do you think?

Also, @NicolasDorier I don't understand the following comment you made, can you clarify? (Also I suppose this point is unrelated to this crypto bug in this issue, right?)

>@goldbe @osagga I should have written more about the escrow voucher idea, it works great but I am not fan of the fact that one creating the voucher is computationally intensive. This is problematic in my latest tests with more than 25 users tumbling together. Is there a quicker way which does not depends on new crypto primitives, I would like to change that.

**Comment by NicolasDorier** [comment]
Yes never mind, il is unrelated. I need to properly document the protocol so we can discuss how to improve TB in v2.

**Comment by osagga** [comment]
@NicolasDorier It looks good! @goldbe I'm just not sure if using the MGF1 would violate any of the crypto proofs in the paper?

**Comment by goldbe** [comment]
No, MGF1 is doing the same as SHA512 in this case.

So looks like we are good.
