### ISSUE TITLE
Tumbling stops working after an hour or two

### ISSUE THREAD

**Issue by Yzord** [NTumbleBit/NTumbleBit#94]
When clients are starting they make cycles and others are also participating into it. After a few hours (mostly 2) the cycles stop and the output on the clients changes. No cycles are being registered and no new block is shown.

[client.txt](https://github.com/NTumbleBit/NTumbleBit/files/1270685/client.txt)

In the text file you see that they are all connecting to the server and making cycles. All of a sudden the cycle output stops.

**Comment by NicolasDorier** [comment]
hey I fixed that today normally. It was caused by a deadlock in my code.

**Comment by Yzord** [comment]
Testing, setting up the clients now...will report after 3 hours

**Comment by Yzord** [comment]
After two hours it seems to be running. I'll wait for the first cycles to finish (37 blocks), but it looks good for now.

**Comment by Yzord** [comment]
Confirmed working.
